[package]
name = "consensus"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.5.0", features = ["sync"] }
log = "0.4.14"
model = { path = "../model" }

[dev-dependencies]
rand = "0.7.3"

